-- Schemas
CREATE SCHEMA IF NOT EXISTS core AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS audit AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS billing AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS config AUTHORIZATION CURRENT_USER;
CREATE SCHEMA IF NOT EXISTS crypto AUTHORIZATION CURRENT_USER;

-- Restrict public schema
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE USAGE ON SCHEMA public FROM PUBLIC;

-- Default privileges so app_role has minimal but sufficient access
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT USAGE ON SEQUENCES TO app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT USAGE, SELECT, INSERT, UPDATE ON TABLES TO app_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA billing GRANT USAGE ON SEQUENCES TO app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT USAGE, SELECT ON TABLES TO app_admin; -- Only admin reads audit by default

ALTER DEFAULT PRIVILEGES IN SCHEMA config GRANT USAGE, SELECT ON TABLES TO app_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA crypto GRANT USAGE ON FUNCTIONS TO app_role;
```
